### ISSUE TITLE
Error reading man page

### ISSUE THREAD

**Issue by lukehatfield** [zenhob/hcl#75]
I just installed this gem successfully. I ran `gem man hcl` and get this response

```
fgets: Undefined error: 0
Error reading man page /Library/Ruby/Gems/2.0.0/gems/hcl-0.4.15/man/hcl.1
No manual entry for /Library/Ruby/Gems/2.0.0/gems/hcl-0.4.15/man/hcl.1
```

Am I doing something wrong? Thank you.

**Comment by zenhob** [comment]
:joy: I was using `write.tap do ... end` instead of `write do ... end` so the file wasn't actually being closed before the end of the job. Good catch, thank you! This will be fixed in the next release.
