### ISSUE TITLE
DNS resolution error

### ISSUE THREAD

**Issue by olets** [zenhob/hcl#85]
Looks like Harvest may have changed something between Oct 20 2017 and today. Running hcl (e.g. `hcl show`, `hcl start ...`) gives me

```
Connection failed. (getaddrinfo: nodename nor servname provided, or not known)
```

**Comment by olets** [comment]
Started wondering whether this could be something introduced by Little Snitch 4's new presets. Not seeing anything obviously problematic in LS's Rules, and I'm not having any other command line connectivity issues, but I think that was right around when I upgraded.

**Comment by zenhob** [comment]
I am closing this, please let me know if the issue persists for you

**Comment by olets** [comment]
Resolved some time since I last tried, which to be fair was quite a while ago. Confirming that it's working now
