### ISSUE TITLE
Add better description to subdomain auth question

### ISSUE THREAD

**Issue by aubreypwd** [zenhob/hcl#91]
Getting:

```
Connection failed. (SSL_connect returned=1 errno=0 state=error: certificate verify failed (error number 1))
``` 

when I run `hcl tasks` or `hcl` anything.

**Comment by aubreypwd** [comment]
Actually, I just fixed this. When being prompted, I entered `xxx.harvestapp.com` as the subdomain during auth not `xxx` which worked.

**Comment by zenhob** [comment]
AUGH THANK YOU this actually just bit me too :D I've added a feature to the config generator to reduce the risk of this happening again
